[package]
name = "rust-fel-example"
version = "0.1.0"
authors = ["Torre Taylor"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.62"

[dependencies.rust-fel]
path = "../" 

