[package]
name = "rust-fel"
version = "0.1.0"
authors = ["Torre Taylor"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.67"

[dependencies.web-sys]
version = "0.3.44"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'NodeList',
  'Window',
  'Text',
]
